Cargo.lock, Cargo.toml, api/Cargo.toml, api/src/api.rs, api/src/error.rs, api/src/lib.rs, api/src/main.rs, api/src/method/get_compressed_account.rs, api/src/method/get_compressed_account_proof.rs, api/src/method/mod.rs, api/src/rpc_server.rs, integration_tests/Cargo.toml, integration_tests/tests/main.rs, integration_tests/tests/utils.rs, lib/dao/src/generated/utxos.rs, lib/migration/src/m20220101_000001_init.rs, lib/migration/src/model/table.rs, lib/persist/Cargo.toml, lib/persist/src/lib.rs
-   Add the new API binary
-   Add getCompressedAccount and getCompressedAccountProof
-   Unit + integration tests
=> Add getCompressedAccount and getCompressedAccountProof API

api/src/api.rs, api/src/method/get_utxo.rs, api/src/method/get_utxos.rs, api/src/method/mod.rs, api/src/method/utils.rs, integration_tests/tests/integration_tests/persist_tests.rs, photon/src/main.rs
Added get_utxo endpoint.
-   Added a test to verify for when there was a matching utxo and when there wasn't. Still missing a test when an UTXO is spent. Added a TODO for that.
=> Add get_utxo endpoint

api/src/method/utils.rs, integration_tests/tests/integration_tests/persist_tests.rs
=> Add slot created field to UTXO response

api/src/api.rs, api/src/method/get_compressed_account_proof.rs, api/src/method/get_utxo_proof.rs, api/src/method/mod.rs, api/src/method/utils.rs
-   Add get_utxo_proof method. Mostly copy paste from get_compressed_account_proof. 
-   Cargo test. Need to add a more thorough test suite here.
=> Add get_utxo_proof method

Cargo.toml, README.md
- Remove outdated instructions
- Add a Local Development section to delineate what's only relevant to Local development
- Improve wording here and there.
- Add more documentation about the different cli options
=> Clean up readme

src/api/rpc_server.rs, src/main.rs
I added `getUtxo`, `getUtxo` and `getUtxoProof` but I forgot to add them to the RPC module.
=> Register missing RPC methods

src/api/api.rs, src/api/method/get_compressed_token_accounts_by_delegate.rs, src/api/method/get_compressed_token_accounts_by_owner.rs, src/api/method/get_utxos.rs, src/api/method/mod.rs, src/api/method/utils.rs, src/api/rpc_server.rs, src/migration/m20220101_000001_init.rs, tests/integration_tests/parsing_tests.rs, tests/integration_tests/persist_tests.rs, tests/integration_tests/snapshots/integration_tests__parsing_tests__e2e_lamport_transfer-A79DKmTDe8VzfRLti3wTi7mbJ9ENZtK7eBHtJ4QYCR2Y-utxos.snap, tests/integration_tests/snapshots/integration_tests__parsing_tests__e2e_lamport_transfer-K75mYjtM3zrpBqBwEtQ1RsM39YULMMMoP1pm5ZQkF2h-utxos.snap, tests/integration_tests/utils.rs
Also eliminated the `total` field since it was redundant and it could be confusing once we introduce pagination.
-   Added tests.
=> Add getCompressedTokenAccountsByDelegate

src/migration/m20220101_000001_init.rs
Removed it as part of the load tests.
=> Re-add sequential primary key

src/ingester/mod.rs, src/ingester/persist/mod.rs
=> Limit size of batch inserts to avoid exceeding parameter 25k limit

tests/integration_tests/utils.rs
-   Summary of changes
-   Testing performed to validate the changes
=> Use database-url when running local test

src/api/error.rs, src/api/method/get_compressed_account_proof.rs, src/api/method/get_compressed_token_accounts_by_delegate.rs, src/api/method/get_compressed_token_accounts_by_owner.rs, src/api/method/get_health.rs, src/api/method/get_multiple_compressed_accounts.rs, src/dao/typedefs/hash.rs, src/dao/typedefs/serializable_pubkey.rs, src/ingester/error.rs, src/ingester/fetchers/poller.rs, src/ingester/mod.rs, src/ingester/parser/mod.rs, src/ingester/persist/mod.rs, src/ingester/persist/state_update.rs, src/ingester/typedefs/block_info.rs, tests/integration_tests/e2e_tests.rs, tests/integration_tests/persist_tests.rs, tests/integration_tests/utils.rs
-   Summary of changes
-   Ran the tests locally
=> General code cleanup based on clippy suggestions

src/api/api.rs, src/api/method/get_compressed_account.rs, src/api/method/get_compressed_balance.rs, src/api/method/get_compressed_program_accounts.rs, src/api/method/get_compressed_token_account_balance.rs, src/api/method/get_compressed_token_accounts_by_delegate.rs, src/api/method/get_compressed_token_accounts_by_owner.rs, src/api/method/get_health.rs, src/api/method/get_multiple_compressed_accounts.rs, src/api/method/utils.rs, src/api/rpc_server.rs, src/migration/m20220101_000001_init.rs, tests/integration_tests/e2e_tests.rs, tests/integration_tests/main.rs, tests/integration_tests/mock_tests.rs, tests/integration_tests/persist_tests.rs
-   Add pagination support for getCompressedAccounts, getCompressedTokenAccountsByOwner and getCompressedTokenAccountsByDelegate
-  Added integration tests for the pagination of the three methods
=> Add pagination support

.github/workflows/publish.yaml, Cargo.lock, Cargo.toml, README.md, src/main.rs, src/migration/main.rs, tests/integration_tests/e2e_tests.rs, tests/integration_tests/mock_tests.rs, tests/integration_tests/utils.rs
-  Renamed photon to photon-indexer since photon was already taken. The name of the binary is still photon though.
-  Add README instructions to run photon 
- Add a Github workflow to publish photon
-   Published Photon. Will test the workflow now.
=> Make necessary changes to publish photon

Cargo.lock, Cargo.toml, src/api/method/get_multiple_compressed_account_proofs.rs, src/api/method/mod.rs, src/api/method/utils.rs, src/dao/generated/accounts.rs, src/ingester/persist/mod.rs, src/migration/m20220101_000001_init.rs, src/migration/model/table.rs, tests/integration_tests/mock_tests.rs, tests/integration_tests/snapshots/integration_tests__e2e_tests__e2e_lamport_transfer.snap
- Added discriminator field to RPC response
- Deleted left over duplicate compressed account proof code 
-  Ran integration tests
=> Add discriminator field to RPC response

src/api/method/utils.rs, src/ingester/fetchers/poller.rs, src/ingester/parser/mod.rs, src/ingester/persist/mod.rs, src/main.rs
- Changed code to gracefully abort indexer handle to avoid emitting errors that make it seem like something has gone wrong
- Reduced logging noise by changing many log messages to debug
- Increased the backfill speed by increasing the max number of concurrent block fetches. Additionally made this an indexer parameter. 
- Improved logging to indicate historical backckfill process
-   Ran indexer
=> Improve indexer ergonomics

src/api/method/utils.rs, src/dao/generated/accounts.rs, src/ingester/persist/mod.rs, src/migration/m20220101_000001_init.rs, src/migration/model/table.rs, tests/integration_tests/snapshots/integration_tests__e2e_tests__e2e_lamport_transfer.snap, tests/integration_tests/snapshots/integration_tests__e2e_tests__e2e_mint_and_transfer-bob-accounts.snap, tests/integration_tests/snapshots/integration_tests__e2e_tests__e2e_mint_and_transfer-charles-accounts.snap
-  Including data hash field in response per Light's request
-   Cargo test
=> Include data hash field in response

Cargo.lock, Cargo.toml, src/api/method/utils.rs, src/dao/generated/accounts.rs, src/ingester/parser/mod.rs, src/ingester/parser/state_update.rs, src/ingester/persist/mod.rs, src/migration/m20220101_000001_init.rs, src/migration/model/table.rs, src/openapi/specs/getCompressedAccount.yaml, src/openapi/specs/getCompressedAccountProof.yaml, src/openapi/specs/getCompressedAccountsByOwner.yaml, src/openapi/specs/getCompressedBalance.yaml, src/openapi/specs/getCompressedTokenAccountBalance.yaml, src/openapi/specs/getCompressedTokenAccountsByDelegate.yaml, src/openapi/specs/getCompressedTokenAccountsByOwner.yaml, src/openapi/specs/getHealth.yaml, src/openapi/specs/getMultipleCompressedAccountProofs.yaml, src/openapi/specs/getMultipleCompressedAccounts.yaml, src/openapi/specs/getSlot.yaml, tests/integration_tests/mock_tests.rs, tests/integration_tests/snapshots/integration_tests__e2e_tests__e2e_lamport_transfer.snap, tests/integration_tests/snapshots/integration_tests__e2e_tests__e2e_mint_and_transfer-bob-accounts.snap, tests/integration_tests/snapshots/integration_tests__e2e_tests__e2e_mint_and_transfer-charles-accounts.snap, tests/integration_tests/utils.rs
- Added leaf_index per request of the Light team
- Updated documentation
- Published new version of the indexer 
-   Updated e2e tests
=> Add missing leaf index field

Cargo.lock, Cargo.toml, src/ingester/fetchers/poller.rs, src/ingester/persist/mod.rs, src/main.rs, tests/data/transactions/compress_lamports/2UPacdoWFmiQovJf2BDamiLSpE9tcLHUFfWrymE7y84n66qUPiN5apQ7hFV4UkRkRYmRgz9oDUetSBttyg4wkGvt, tests/data/transactions/compress_lamports/jyBWSng9SMwsZ4n7S3jEEhCzBPN8gExhSuZ2yzN7No3RsfUAPefgcGVdJVBBs8fLEuQ3amqAEs9XNjYiQLqz1EC, tests/integration_tests/e2e_tests.rs, tests/integration_tests/snapshots/integration_tests__e2e_tests__compress_lamports.snap
- Use confirmed commitment level instead of finalized
- Fix a one-off error in the transaction poller
- Improve debugging messages 
- Published a new version of Photon
-  Ran the e2e Light tests using Photon. 
- Added a new integration test.
=> Photon E2E bug fixes

Cargo.lock, Cargo.toml
-   Pin time version to resolve https://github.com/launchbadge/sqlx/issues/3189
-   Cargo publish and cargo install
=> Pin time version

src/api/api.rs, src/api/method/get_compressed_balance.rs, src/api/method/get_compressed_balance_by_owner.rs, src/api/method/get_compressed_token_account_balance.rs, src/api/method/get_compressed_token_balances_by_owner.rs, src/api/method/get_indexer_slot.rs, src/api/method/utils.rs, src/common/typedefs/account.rs, src/common/typedefs/mod.rs, src/common/typedefs/token_data.rs, src/common/typedefs/unix_timestamp.rs, src/common/typedefs/unsigned_integer.rs, src/ingester/parser/mod.rs, src/ingester/persist/mod.rs, src/openapi/mod.rs, tests/integration_tests/e2e_tests.rs, tests/integration_tests/mock_tests.rs
If you use native integer types, then Gitbook doesn't assign a default value. 
-  Cargo test
=> Add unix timestamp and unsigned integer types for better documentation

.gitignore, src/api/method/get_multiple_compressed_account_proofs.rs, src/dao/generated/indexed_trees.rs, src/ingester/persist/mod.rs, src/ingester/persist/persisted_indexed_merkle_tree.rs, src/ingester/persist/persisted_state_tree.rs, src/main.rs, src/migration/m20220101_000001_init.rs, src/migration/model/table.rs, tests/integration_tests/mock_tests.rs
Implemented persisted indexed merkle trees to support exclusion proofs. 
Added tests
=> Implement persisted indexed merkle trees

src/api/api.rs, src/api/method/get_validity_proof.rs, src/api/method/utils.rs, src/ingester/indexer/mod.rs, src/main.rs, tests/integration_tests/mock_tests.rs, tests/integration_tests/utils.rs
-  Added a parameter so users can specify the prover url. 
-  Added disable indexing and disable API parameters
- Changed Photon to start from the last indexed slot in the database plus 1.
=> Command line improvements

README.md
Resolved https://github.com/helius-labs/photon/issues/123
=> Add documentation for installing dependencies

Cargo.lock, Cargo.toml, src/api/method/get_compressed_accounts_by_owner.rs, tests/integration_tests/prod_tests.rs
-   We are panicking if the user inputs a null filter. This is a bug. In this PR, I update the code so that we throw a validation error instead.
=> Throw validation error instead of panicking

src/migration/migrations/standard/m20220101_000001_init.rs
=> Increase size of bigint2 numeric

Cargo.lock, Cargo.toml, src/api/method/get_compressed_account_proof/v2.rs, src/api/method/get_compressed_accounts_by_owner/common.rs, src/api/method/get_multiple_compressed_account_proofs/v2.rs
=> chore: bump light dependencies
